@Library('Shared') _
pipeline {
    agent any
    
    environment{
        GIT_URL = "https://github.com/syedmehfooz47/tomato-devops.git"
        GIT_BRANCH = "main"
        GIT_CREDENTIALS = "Github-Credentials"
    }

    parameters {
        string(name: 'DOCKER_TAG', defaultValue: '', description: 'Docker tag of the image built by the CI job')
    }

    stages {
        stage("Workspace cleanup"){
            steps{
                script{
                    cleanWs()
                }
            }
        }
        
        stage('Git: Code Checkout') {
            steps {
                script{
                    code_checkout(env.GIT_URL,env.GIT_BRANCH)
                }
            }
        }
        
        stage('Verify: Docker Image Tags') {
            steps {
                script{
                    echo "DOCKER_TAG: ${params.DOCKER_TAG}"
                }
            }
        }
        
        stage("Update: Kubernetes manifests"){ 
            steps{
                script{
                    dir('kubernetes'){
                        sh """
                            sed -i -e s/tomato-backend.*/tomato-backend:${params.DOCKER_TAG}/g backend.yml
                            sed -i -e s/tomato-admin.*/tomato-admin:${params.DOCKER_TAG}/g admin.yml
                            sed -i -e s/tomato-frontend.*/tomato-frontend:${params.DOCKER_TAG}/g frontend.yml
                        """
                    }
                }
            }
        }
        
        stage("Git: Code update and push to GitHub"){
            steps{
                script{
                    withCredentials([gitUsernamePassword(credentialsId: env.GIT_CREDENTIALS, gitToolName: 'Default')]) {
                        sh """
                        echo "Checking repository status: "
                        git status
                    
                        echo "Adding changes to git: "
                        git add .
                        
                        git config user.email "syedmehfoozcs@gmail.com"
                        git config user.name "syedmehfooz47"

                        echo "Commiting changes: "
                        git commit -m "Update Kubernetes manifests [skip ci]"
                        
                        echo "Pushing changes to github: "
                        git push ${env.GIT_URL} ${env.GIT_BRANCH}
                        """
                    }
                }
            }
        }
    }
  post {
        always {
            generate_reports(projectName: 'Tomato-CD', imageName: 'tomato-frontend, tomato-backend, tomato-admin', imageTag: "${params.DOCKER_TAG},${params.DOCKER_TAG},${params.DOCKER_TAG}")
        }
        success {
            script {
                emailext attachLog: true,
                attachmentsPattern: 'reports/build-report.txt',
                from: 'jenkins@alerts.syedmehfooz.com',
                subject: "Tomato Application has been updated and deployed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                        <div style="background-color: #87CEEB; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">URL: ${env.BUILD_URL}</p>
                        </div>
                    </body>
                    </html>
            """,
            to: 'hello@syedmehfooz.com',
            mimeType: 'text/html'
            }
        }
      failure {
            script {
                emailext attachLog: true,
                attachmentsPattern: 'reports/build-report.txt',
                from: 'jenkins@alerts.syedmehfooz.com',
                subject: "Tomato Application build failed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                    </body>
                    </html>
            """,
            to: 'hello@syedmehfooz.com',
            mimeType: 'text/html'
            }
        }
    }
}